### ISSUE TITLE
Generating figures for Feature comparison

### ISSUE THREAD

**Issue by YasminAMassoud** [garethjns/Kaggle-EEG#19]
![image](https://user-images.githubusercontent.com/55138409/107516460-1f1a4500-6bb5-11eb-997d-7cc15e0361fc.png)

How are These plotted ? 

Thanks

**Comment by garethjns** [comment]
Hi @YasminAMassoud, that figure was generated manually, I don't think the code is anywhere in the repo. It shows the mean importance (either gain or number of splits, I forget) for each feature in the random forest model. The top figure is for all the features, unlabelled but grouped by window size. The bottom figure are the top 20 features, with labels.
